name: validasi
description: An easy to use and flexible validation library for Dart and Flutter. Easily validate your forms input with built-in rules or create your own.
version: 0.0.9
repository: https://github.com/albetnov/validasi
homepage: https://albetnov.github.io/validasi

topics:
  - validation
  - form

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  email_validator: ^3.0.0
  intl: ">=0.19.0 <0.21.0"
  meta: ^1.15.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.12
  lints: ">=4.0.0 <6.0.0"
  mockito: ^5.4.4
  test: ^1.24.0
