name: validasi_annotation
description: Annotations for Validasi - used to trigger code generation.
version: 0.1.0-dev.3
repository: https://github.com/albetnov/validasi
homepage: https://albetnov.github.io/validasi

topics:
  - validation
  - annotations
  - codegen

environment:
  sdk: ^3.5.0
resolution: workspace

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
