name: validasi_gen_example
publish_to: none
version: 0.1.0-dev.2

environment:
  sdk: ^3.5.0
resolution: workspace

dependencies:
  validasi:
    path: ../../validasi
  validasi_annotation:
    path: ../../validasi_annotation

dev_dependencies:
  build_runner: ^2.4.12
  test: ^1.24.0
  validasi_gen:
    path: ../


