builders:
  validasi:
    import: "package:validasi_gen/src/builder.dart"
    builder_factories:
      - validasiBuilder
    build_extensions:
      ".dart":
        - ".validasi.dart"
    auto_apply: dependents
    build_to: source
